# Generated by Django 5.2.7 on 2025-10-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='contexto',
            field=models.CharField(default='login', max_length=20),
        ),
        migrations.AddField(
            model_name='codigoverificacion',
            name='usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codigoverificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
